# -*- coding: utf-8 -*-
"""CALCULADORA MV - DBM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P3YMr3qDIrKAVMzy-q4k22Pl4LkzWDRn
"""

import matplotlib.pyplot as plt
import numpy as np

plt.style.use("seaborn-poster")

from scipy import signal

f = 5                                               #frecuencia = 5Hz
t = np.linspace(0, 1, 1000)                         # Desde 0 hasta 1, representando 50 puntos - vector del tiempo
y = signal.square(2 * np.pi * f * t)

plt.figure(figsize = (10 , 6))                      # se define el tamaño de la figura
plt.plot(t,y,'g')
plt.title('Square wave: s(t) = square (2πft)')
plt.xlabel("Time")
plt.ylabel("Amplitude")
plt.axhline(y=0, color='k')
plt.show()

print(len(t))

# potencia en mV

import numpy as np

Pdbm = float(input("Digite el valor de la potencia en (dBm): "))
PmV = 10**(Pdbm / 10)
print(f"La potencia en mV es: {PmV}")

import numpy as np

PmV = float(input("Digite el valor de la potencia en (mV): "))
Pdbm = 10*(np.log10(PmV))
print(f"La potencia en dBm es: {Pdbm}")

