# -*- coding: utf-8 -*-
"""EJERCICIO 30/09 - LONGITUD DE ONDA .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uy-1y6vIY2JM-iInGKQKFdNYKekxTEnx
"""

import numpy as np
import matplotlib.pyplot as plt

F = 60                                 # frecuencia
A = 170                                # amplitud
T = 1/60                               # periodo
c = 300000                             # Velocidad de la luz en km/
V = 0.9 * c

L = V * T                              # formula para lambda
print(f"λ = {np.round(L,0)} Km")
print(f"λ = {int(L)} km ")             # valor en entero

import numpy as np
import matplotlib.pyplot as plt

A = 172
F = 500
T = 1/60
t = np.round(T*1000,1)                                 #redondeo del tiempo a una cifra
x = np.linspace(0,t,50)

y = A * np.sin(2 *np.pi * F * x )
rms = np.sqrt(np.mean(np.square(y)))
                                                       # print(f"rms {np.round(rms,0)} ")
print(f"{int(rms)} v")

plt.figure(figsize=(10,6))
                                       #valor del rms en int
plt.plot(x,y,'g')
plt.axhline()
plt.xlabel("Time (s) ")
plt.ylabel("Amplitud (dBm)")
plt.title("Electric ")
plt.show();