# -*- coding: utf-8 -*-
"""OTRAS FORMAS DE ONDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Yl8A2qjXoqEmCpbNaaKgblemix2zQX7
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy import signal

t= np.linspace(-1,1,2*100, endpoint = False)        #TIME SERIES
F = 10;                                             #FRECUENCY
i, q, e = signal.gausspulse(t, F, retquad=True, retenv=True)
plt.plot(t,i,t,q,t,e,'--' )
plt.show

plt.style.use("seaborn-poster")

import numpy as np

from scipy import signal
import matplotlib.pyplot as plt

t = np.linspace(0, 1, 500)
plt.plot(t, signal.sawtooth(20 * np.pi * 2 * t))
plt.show()

from scipy.signal import chirp, spectrogram
import matplotlib.pyplot as plt
import numpy as np


t = np.linspace(0, 10, 1000)
w = chirp(t, f0=6, f1=2, t1=3, method='linear')
plt.plot(t, w)
plt.title("Linear Chirp")
plt.xlabel('t (sec)')
plt.show()

