# -*- coding: utf-8 -*-
"""SEÑAL ANALOGA 4.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X99R1wBBT9eItGcqGq-Cqt0tc_rICWIx
"""

import numpy as np
import matplotlib.pyplot as plt

plt.style.use("seaborn-poster")

A = [1,0.5,1,1]                      #AMPLITUD
F = [1,1,2,1]                        #FRECUENCIA
phi = [0,0,0, (np.pi*F[3]/2)]        #FASE
t = np.linspace(0, 1, 200)             #SERIES DE TIEMPO

y1 = A[0] * np.sin(2*np.pi * F[0] * t + phi[0])
y2 = A[1] * np.sin(2*np.pi * F[1] * t + phi[1])
y3 = A[2] * np.sin(2*np.pi * F[2] * t + phi[2])
y4 = A[3] * np.sin(2*np.pi * F[3] * t + phi[3])

fig, ax = plt.subplots(2,2)
fig.tight_layout(pad = 3.5)
fig.subplots_adjust(bottom=0.1,right=1.2,top=1.2)

#subplots
ax[0,0].plot(t,y1,color='tab:blue')
ax[0,1].plot(t,y2,color='tab:orange')
ax[1,0].plot(t,y3,color='tab:green')
ax[1,1].plot(t,y4,color='tab:purple')

fig.show()
case = 1
for i in range(0,2):
  for j in range(0,2):
    ax[i,j].set_ylabel("Amplitud(dBm)")
    ax[i,j].set_xlabel("Time (s)")
    ax[i,j].axhline(y=0,color='k')
    ax[i,j].set_title('Case: ' + str(case) + ': (t) = A sin (2πft) + φ')
    case += 1